# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab9bc34eb501f73d754466ac143d5c1ce97dee2e0d6a7033e8a59121cc62c9f80682f4cede4b03bc6a273952bcdfd0933323a07d23de0f0bedc695e9212be8b2

test:
  secret_key_base: 34c3fb87b886a976fa11e22ca3b92a7163532cf41450583593bd7c8c41a8730cfded200eed863d188bf77e61d96c3bc1e9eec730d2f4e04c25cc84f4b80bc044

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
